version: '3'
services:
    db:
        container_name: db
        privileged: true
        restart: always
        image: postgres
        environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=inn0v@tion_p@ssw0rd
        - POSTGRES_DB=innovation_db
        ports:
            - 5432:5432
        volumes:
        - ${DB_DATA}:/var/lib/postgresql/data
    webservice:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/project_code
        depends_on:
            - redis
    redis:
        image: redis
    portal:
        command: python manage.py runserver 0.0.0.0:8990
        ports:
        - "8990:8990"
        depends_on:
        - db
